name: ${project.name}
version: ${project.version}
author: [ProgrammerDan]
main: com.programmerdan.minecraft.addgun.AddGun
commands:
 addgun:
  description: Shows the commands useable for this plugin
  usage: |
   The following are commands available for use:
   /givegun <player> <gun>
   /givebullet <player> <bullet> [<amount>]
   /giveclip <player> <clip>
   /repairgun <player>
  alias: agun
  permission: addgun.*
 givegun:
  description: Gives player a weapon.
  usage: |
   /givegun <player> <gun>
  alias: ag.give
  permission: addgun.give
 givebullet:
  description: Gives player a bullet for a weapon.
  usage: |
   /givebullet <player> <bullet> <amount>
  alias: ag.gb
  permission: addgun.give
 giveclip:
  description: Gives player a clip for a weapon
  usage: | 
   /giveclip <player> <clip>
  alias: ag.gc
  permission: addgun.give
 repairgun:
  description: Repairs a player's held gun
  usage: |
   /repairgun <player>
  alias: ag.rg
  permission: addgun.repair
permissions:
 addgun.*:
  description: Gives access to all Addgun commands
  default: op
  children:
   addgun.give: true
  addgun.give:
   description: Allows gifting players specific weapons
   default: op
  addgun.repair:
   description: Allows repairing a gun
   default: op
  addgun.data:
   description: Allows insight into special data as weapons are used
   default: op
